"""Render HTML previews of the Excel workbooks generated by the Excel writer."""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from src.core.utils import html_value, safe_slug, write_text

from src.reporting.html.page_shell import (
    href_relative,
    index_back_link,
    render_page,
    tabbed_sections,
)


LogCallback = Callable[[str], None]


def build_excel_preview_sections(workbook) -> list[tuple[str, str]]:
    """Convert each sheet of ``workbook`` into a (label, html_table) tuple."""

    max_rows = 500
    sections: list[tuple[str, str]] = []
    for sheet in workbook.worksheets:
        headers: tuple | None = None
        body_rows: list[str] = []
        for index, row in enumerate(sheet.iter_rows(values_only=True)):
            if index >= max_rows:
                body_rows.append(
                    f"<tr><td colspan='{len(headers) if headers else 1}' "
                    "class='empty'>... (apercu tronque a "
                    f"{max_rows} lignes) ...</td></tr>"
                )
                break
            if index == 0:
                headers = row
                continue
            cells = "".join(
                f"<td>{html_value('' if value is None else value)}</td>"
                for value in row
            )
            body_rows.append(f"<tr>{cells}</tr>")

        if headers:
            header_cells = "".join(
                f"<th>{html_value('' if value is None else value)}</th>"
                for value in headers
            )
            table = (
                f"<table><thead><tr>{header_cells}</tr></thead>"
                f"<tbody>{''.join(body_rows)}</tbody></table>"
            )
        else:
            table = "<p class='empty'>Feuille vide.</p>"

        label = sheet.title or "Feuille"
        sections.append((label, table))

    if not sections:
        sections.append(
            ("Contenu", "<p class='empty'>Aucune feuille exploitable.</p>")
        )
    return sections


def write_excel_preview_pages(
    output_dir: Path,
    assets_dir: Path,
    log: LogCallback,
) -> dict[Path, Path]:
    """Generate one HTML preview alongside every ``.xlsx`` in ``output_dir/excel``."""

    excel_dir = output_dir / "excel"
    html_excel_dir = output_dir / "html" / "excel"
    mapping: dict[Path, Path] = {}
    if not excel_dir.exists():
        return mapping

    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        log(f"openpyxl indisponible, apercu Excel ignore: {exc}")
        return mapping

    for xlsx_path in sorted(excel_dir.glob("*.xlsx")):
        try:
            workbook = load_workbook(xlsx_path, read_only=True, data_only=True)
        except Exception as exc:
            log(f"Echec lecture {xlsx_path.name}: {exc}")
            continue
        try:
            sections = build_excel_preview_sections(workbook)
        finally:
            workbook.close()
        
        preview_path = html_excel_dir / f"{xlsx_path.stem}.html"
        tabs = tabbed_sections(
            f"excel-preview-{safe_slug(xlsx_path.stem)}", sections
        )
        xlsx_href = href_relative(preview_path, xlsx_path)
        body = f"""
{index_back_link(preview_path, output_dir / "html", "exports-excel")}
<h1>{html_value(xlsx_path.name)}</h1>
<p>Apercu des feuilles du classeur. <a href="{xlsx_href}">Telecharger le fichier Excel original</a>.</p>
{tabs}
""".strip()
        write_text(
            preview_path,
            render_page(
                xlsx_path.stem,
                body,
                preview_path,
                assets_dir,
                include_mermaid=False,
            ),
        )
        mapping[xlsx_path] = preview_path
    if mapping:
        log(f"{len(mapping)} apercu(s) HTML de classeur Excel genere(s).")
    return mapping
